import { z } from "zod"
import { BankAccountLineSchema } from "./BankAccountLine.interface"

export const BankAccountSchema = z
	.object({
		label: z.string(),
		courant: z.string(),
		type: z.string(),
		bank: z.string(),
		clos: z.string(),
		rappro: z.string(),
		url: z.any(),
		code_banque: z.string(),
		code_guichet: z.string(),
		number: z.string(),
		cle_rib: z.string(),
		bic: z.string(),
		iban: z.string(),
		iban_prefix: z.any(),
		domiciliation: z.string(),
		pti_in_ctti: z.string(),
		proprio: z.string(),
		owner_address: z.string(),
		state_id: z.any(),
		type_lib: z.array(z.string()),
		status: z.array(z.string()),
		account_number: z.string(),
		fk_accountancy_journal: z.any(),
		accountancy_journal: z.any(),
		currency_code: z.string(),
		account_currency_code: z.string(),
		min_allowed: z.string(),
		min_desired: z.string(),
		comment: z.string(),
		date_solde: z.any(),
		ics: z.string(),
		ics_transfer: z.string(),
		id: z.string(),
		entity: z.any(),
		import_key: z.any(),
		array_options: z.array(z.any()),
		array_languages: z.any(),
		contacts_ids: z.any(),
		linked_objects: z.any(),
		linkedObjectsIds: z.any(),
		canvas: z.any(),
		fk_project: z.any(),
		contact_id: z.any(),
		user: z.any(),
		origin: z.any(),
		origin_id: z.any(),
		ref: z.string(),
		ref_ext: z.any(),
		statut: z.any(),
		country_id: z.string(),
		country_code: z.string(),
		region_id: z.any(),
		barcode_type: z.any(),
		barcode_type_coder: z.any(),
		mode_reglement_id: z.any(),
		cond_reglement_id: z.any(),
		demand_reason_id: z.any(),
		transport_mode_id: z.any(),
		shipping_method_id: z.any(),
		model_pdf: z.any(),
		last_main_doc: z.any(),
		fk_bank: z.any(),
		fk_account: z.any(),
		note_public: z.any(),
		note_private: z.any(),
		total_ht: z.any(),
		total_tva: z.any(),
		total_localtax1: z.any(),
		total_localtax2: z.any(),
		total_ttc: z.any(),
		lines: z.array(BankAccountLineSchema),
		name: z.any(),
		lastname: z.any(),
		firstname: z.any(),
		civility_id: z.any(),
		date_creation: z.number(),
		date_validation: z.any(),
		date_modification: z.any(),
		date_cloture: z.any(),
		user_author: z.any(),
		user_creation: z.any(),
		user_creation_id: z.any(),
		user_valid: z.any(),
		user_validation: z.any(),
		user_validation_id: z.any(),
		user_closing_id: z.any(),
		user_modification: z.any(),
		user_modification_id: z.any(),
		specimen: z.number(),
		solde: z.number(),
		date_update: z.number(),
	})
	.partial()
	.catchall(z.any())

export interface BankAccount extends z.infer<typeof BankAccountSchema> {}
