import { z } from "zod"

export const BankAccountLineSchema = z
	.object({
		id: z.string(),
		ref: z.string(),
		datec: z.string(),
		dateo: z.string(),
		datev: z.string(),
		amount: z.string(),
		amount_main_currency: z.any(),
		fk_user_author: z.string(),
		fk_user_rappro: z.any(),
		fk_type: z.string(),
		fk_bordereau: z.string(),
		fk_account: z.string(),
		bank_account_ref: z.string(),
		bank_account_label: z.string(),
		numero_compte: z.any(),
		emetteur: z.any(),
		rappro: z.string(),
		num_releve: z.any(),
		num_chq: z.any(),
		bank_chq: z.any(),
		label: z.string(),
		entity: z.any(),
		import_key: z.any(),
		array_options: z.array(z.any()),
		array_languages: z.any(),
		contacts_ids: z.any(),
		linked_objects: z.any(),
		linkedObjectsIds: z.any(),
		canvas: z.any(),
		fk_project: z.any(),
		contact_id: z.any(),
		user: z.any(),
		origin: z.any(),
		origin_id: z.any(),
		ref_ext: z.any(),
		statut: z.any(),
		status: z.any(),
		country_id: z.any(),
		country_code: z.any(),
		state_id: z.any(),
		region_id: z.any(),
		barcode_type: z.any(),
		barcode_type_coder: z.any(),
		mode_reglement_id: z.any(),
		cond_reglement_id: z.any(),
		demand_reason_id: z.any(),
		transport_mode_id: z.any(),
		shipping_method_id: z.any(),
		model_pdf: z.any(),
		last_main_doc: z.any(),
		fk_bank: z.any(),
		note_public: z.any(),
		note_private: z.any(),
		total_ht: z.any(),
		total_tva: z.any(),
		total_localtax1: z.any(),
		total_localtax2: z.any(),
		total_ttc: z.any(),
		lines: z.any(),
		name: z.any(),
		lastname: z.any(),
		firstname: z.any(),
		civility_id: z.any(),
		date_creation: z.any(),
		date_validation: z.any(),
		date_modification: z.any(),
		date_cloture: z.any(),
		user_author: z.any(),
		user_creation: z.any(),
		user_creation_id: z.any(),
		user_valid: z.any(),
		user_validation: z.any(),
		user_validation_id: z.any(),
		user_closing_id: z.any(),
		user_modification: z.any(),
		user_modification_id: z.any(),
		specimen: z.number(),
	})
	.partial()
	.catchall(z.any())

export interface BankAccountLine extends z.infer<typeof BankAccountLineSchema> {}
