import { z } from "zod"

export const ContactSchema = z
	.object({
		civility_id: z.any(),
		civility_code: z.any(),
		civility: z.any(),
		civilite: z.any(),
		address: z.any(),
		zip: z.any(),
		town: z.any(),
		state_id: z.any(),
		poste: z.any(),
		socid: z.any(),
		fk_soc: z.any(),
		statut: z.any(),
		code: z.any(),
		email: z.any(),
		url: z.any(),
		no_email: z.any(),
		socialnetworks: z.array(z.any()),
		skype: z.any(),
		twitter: z.any(),
		facebook: z.any(),
		linkedin: z.any(),
		jabberid: z.any(),
		photo: z.any(),
		phone_pro: z.any(),
		phone_perso: z.any(),
		phone_mobile: z.any(),
		fax: z.any(),
		priv: z.any(),
		birthday: z.any(),
		default_lang: z.any(),
		ref_facturation: z.any(),
		ref_contrat: z.any(),
		ref_commande: z.any(),
		ref_propal: z.any(),
		user_id: z.any(),
		user_login: z.any(),
		roles: z.array(z.any()),
		cacheprospectstatus: z.array(z.any()),
		fk_prospectlevel: z.any(),
		stcomm_id: z.any(),
		statut_commercial: z.any(),
		stcomm_picto: z.any(),
		id: z.any(),
		entity: z.any(),
		validateFieldsErrors: z.array(z.any()),
		import_key: z.any(),
		array_options: z.array(z.any()),
		array_languages: z.any(),
		contacts_ids: z.any(),
		linked_objects: z.any(),
		linkedObjectsIds: z.any(),
		linkedObjectsFullLoaded: z.array(z.any()),
		canvas: z.any(),
		fk_project: z.any(),
		fk_projet: z.any(),
		contact_id: z.any(),
		user: z.any(),
		origin: z.any(),
		origin_id: z.any(),
		ref: z.any(),
		ref_ext: z.any(),
		status: z.any(),
		country_id: z.any(),
		country_code: z.any(),
		region_id: z.any(),
		barcode_type: z.any(),
		barcode_type_coder: z.any(),
		mode_reglement_id: z.any(),
		cond_reglement_id: z.any(),
		demand_reason_id: z.any(),
		transport_mode_id: z.any(),
		shipping_method_id: z.any(),
		model_pdf: z.any(),
		last_main_doc: z.any(),
		fk_bank: z.any(),
		fk_account: z.any(),
		note_public: z.any(),
		note_private: z.any(),
		name: z.any(),
		lastname: z.any(),
		firstname: z.any(),
		date_creation: z.any(),
		date_validation: z.any(),
		date_modification: z.any(),
		date_cloture: z.any(),
		user_author: z.any(),
		user_creation: z.any(),
		user_creation_id: z.any(),
		user_valid: z.any(),
		user_validation: z.any(),
		user_validation_id: z.any(),
		user_closing_id: z.any(),
		user_modification: z.any(),
		user_modification_id: z.any(),
		specimen: z.any(),
		field: z
			.object({
				fk_stcommcontact: z.object({
					enabled: z.any(),
				}),
				fk_prospectcontactlevel: z.object({
					enabled: z.any(),
				}),
			})
			.partial(),
		socname: z.any(),
		mail: z.any(),
		gender: z.any(),
	})
	.partial()
	.catchall(z.any())

export interface Contact extends z.infer<typeof ContactSchema> {}
