import { z } from "zod"

export const ShipmentLineSchema = z
	.object({
		line_id: z.any(),
		origin_line_id: z.any(),
		fk_origin: z.any(),
		fk_origin_line: z.any(),
		fk_expedition: z.any(),
		qty: z.any(),
		qty_shipped: z.any(),
		fk_product: z.any(),
		detail_batch: z.array(z.any()),
		details_entrepot: z.array(
			z
				.object({
					entrepot_id: z.any(),
					qty_shipped: z.any(),
					line_id: z.any(),
				})
				.partial()
		),
		entrepot_id: z.any(),
		qty_asked: z.any(),
		ref: z.any(),
		product_ref: z.any(),
		libelle: z.any(),
		product_label: z.any(),
		desc: z.any(),
		product_desc: z.any(),
		product_type: z.any(),
		rang: z.any(),
		weight: z.any(),
		weight_units: z.any(),
		length: z.any(),
		length_units: z.any(),
		surface: z.any(),
		surface_units: z.any(),
		volume: z.any(),
		volume_units: z.any(),
		id: z.any(),
		rowid: z.any(),
		fk_unit: z.any(),
		date_debut_prevue: z.any(),
		date_debut_reel: z.any(),
		date_fin_prevue: z.any(),
		date_fin_reel: z.any(),
		width: z.any(),
		width_units: z.any(),
		height: z.any(),
		height_units: z.any(),
		multilangs: z.any(),
		product: z.any(),
		product_barcode: z.any(),
		fk_product_type: z.any(),
		duree: z.any(),
		info_bits: z.any(),
		special_code: z.any(),
		entity: z.any(),
		import_key: z.any(),
		array_options: z.array(z.any()),
		array_languages: z.any(),
		contacts_ids: z.any(),
		linked_objects: z.any(),
		linkedObjectsIds: z.any(),
		canvas: z.any(),
		origin: z.any(),
		origin_id: z.any(),
		ref_ext: z.any(),
		statut: z.any(),
		status: z.any(),
		state_id: z.any(),
		region_id: z.any(),
		demand_reason_id: z.any(),
		transport_mode_id: z.any(),
		last_main_doc: z.any(),
		fk_bank: z.any(),
		fk_account: z.any(),
		lines: z.any(),
		date_creation: z.any(),
		date_validation: z.any(),
		date_modification: z.any(),
		date_cloture: z.any(),
		user_author: z.any(),
		user_creation: z.any(),
		user_creation_id: z.any(),
		user_valid: z.any(),
		user_validation: z.any(),
		user_validation_id: z.any(),
		user_closing_id: z.any(),
		user_modification: z.any(),
		user_modification_id: z.any(),
		specimen: z.any(),
		product_tosell: z.any(),
		product_tobuy: z.any(),
		product_tobatch: z.any(),
		label: z.any(),
		description: z.any(),
		pa_ht: z.any(),
		localtax1_tx: z.any(),
		localtax2_tx: z.any(),
		price: z.any(),
		subprice: z.any(),
	})
	.partial()
	.catchall(z.any())

export interface ShipmentLine extends z.infer<typeof ShipmentLineSchema> {}
